StickersTemplate.Configuration/Models/Sticker.cs
//----------------------------------------------------------------------------------------------
// <copyright file="Sticker.cs" company="Microsoft">
// Copyright (c) Microsoft. All rights reserved.
// </copyright>
//----------------------------------------------------------------------------------------------

namespace StickersTemplate.Configuration.Models
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Sticker
    /// </summary>
    public class Sticker
    {
        /// <summary>
        /// Maximum dimension of a sticker in pixels
        /// </summary>
        public const int MaximumDimensionInPixels = 640;

        /// <summary>
        /// Gets or sets Id
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets ImageUri
        /// </summary>
        public Uri ImageUri { get; set; }

        /// <summary>
        /// Gets or sets Name
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets Keywords
        /// </summary>
        public IList<string> Keywords { get; set; }

        /// <summary>
        /// Gets or sets Index
        /// </summary>
        public int Index { get; set; }

        /// <summary>
        /// Gets or sets State
        /// </summary>
        public StickerState State { get; set; }
    }
}

StickersTemplate.Configuration/Models/StickerViewModel.cs
//----------------------------------------------------------------------------------------------
// <copyright file="StickerViewModel.cs" company="Microsoft">
// Copyright (c) Microsoft. All rights reserved.
// </copyright>
//----------------------------------------------------------------------------------------------

namespace StickersTemplate.Configuration.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Web;

    /// <summary>
    /// Sticker View Model
    /// </summary>
    public class StickerViewModel
    {
        private string name;

        /// <summary>
        /// Initializes a new instance of the <see cref="StickerViewModel"/> class.
        /// </summary>
        public StickerViewModel()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StickerViewModel"/> class.
        /// </summary>
        /// <param name="sticker">Sticker</param>
        public StickerViewModel(Sticker sticker)
        {
            this.Id = sticker.Id;
            this.ImageUri = sticker.ImageUri;
            this.Name = sticker.Name;
            this.Keywords = string.Join(", ", sticker.Keywords ?? Enumerable.Empty<string>());
            this.Index = sticker.Index;
            this.State = sticker.State;
        }

        /// <summary>
        /// Gets or sets Id
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets ImageUri
        /// </summary>
        [Display(Name = "Image")]
        public Uri ImageUri { get; set; }

        /// <summary>
        /// Gets or sets Name
        /// </summary>
        public string Name
        {
            get { return this.name; }
            set { this.name = value?.Trim(); }
        }

        /// <summary>
        /// Gets or sets Keywords
        /// </summary>
        public string Keywords { get; set; }

        /// <summary>
        /// Gets or sets Index
        /// </summary>
        public int Index { get; set; }

        /// <summary>
        /// Gets or sets State
        /// </summary>
        public StickerState State { get; set; }

        /// <summary>
        /// Gets or sets File
        /// </summary>
        public HttpPostedFileBase File { get; set; }

        /// <summary>
        /// Get Keywords List
        /// </summary>
        /// <returns>Keywords List</returns>
        public List<string> GetKeywordsList()
        {
            return this.Keywords?.Split(new char[] { ',', ' ' }, StringSplitOptions.RemoveEmptyEntries)
                .Select(s => s.Trim())
                .Distinct(StringComparer.InvariantCultureIgnoreCase)
                .ToList();
        }
    }
}

StickersTemplate.Configuration/Controllers/StickersController.cs
//----------------------------------------------------------------------------------------------
// <copyright file="StickersController.cs" company="Microsoft">
// Copyright (c) Microsoft. All rights reserved.
// </copyright>
//----------------------------------------------------------------------------------------------

namespace StickersTemplate.Configuration.Controllers
{
    using System;
    using System.Data;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using ImageResizer;
    using Microsoft.Azure;
    using Newtonsoft.Json;
    using StickersTemplate.Configuration.Models;
    using StickersTemplate.Configuration.Providers;
    using StickersTemplate.Configuration.Providers.Serialization;

    /// <summary>
    /// Stickers Controller
    /// </summary>
    [Authorize]
    public class StickersController : Controller
    {
        private readonly IStickerStore stickerStore;
        private readonly IBlobStore blobStore;

        /// <summary>
        /// Initializes a new instance of the <see cref="StickersController"/> class.
        /// </summary>
        public StickersController()
        {
            var connectionString = CloudConfigurationManager.GetSetting("StorageConnectionString");
            this.stickerStore = new StickerStore(connectionString, CloudConfigurationManager.GetSetting("StickersTableName"));
            this.blobStore = new BlobStore(connectionString, CloudConfigurationManager.GetSetting("StickersBlobContainerName"));
        }

        /// <summary>
        /// GET: Stickers
        /// </summary>
        /// <returns>Task Action Result</returns>
        public async Task<ActionResult> Index()
        {
            var stickers = await this.stickerStore.GetStickersAsync();
            var activeStickers = stickers.Where(s => s.State == StickerState.Active);
            return this.View(activeStickers.Select(s => new StickerViewModel(s)));
        }

        /// <summary>
        /// GET: Stickers/Create
        /// </summary>
        /// <returns>Action Result</returns>
        public ActionResult Create()
        {
            return this.View();
        }

        /// <summary>
        /// POST: Stickers/Create
        /// To protect from overposting attacks, please enable the specific properties you want to bind to, for
        /// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        /// </summary>
        /// <param name="stickerViewModel">Sticker View Model</param>
        /// <returns>Task Action Result</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "File,Name,Keywords")] StickerViewModel stickerViewModel)
        {
            if (this.ModelState.IsValid)
            {
                var id = Guid.NewGuid().ToString("D");
                Uri imageUri;

                if (Path.GetExtension(stickerViewModel.File.FileName).ToLower() == ".gif")
                {
                    imageUri = await this.blobStore.UploadBlobAsync(id, stickerViewModel.File.InputStream);
                }
                else
                {
                    // Resize the image to fit within the maximum dimensions
                    using (var memoryStream = new MemoryStream())
                    {
                        ImageBuilder.Current.Build(stickerViewModel.File, memoryStream, new ResizeSettings($"maxwidth={Sticker.MaximumDimensionInPixels}&maxheight={Sticker.MaximumDimensionInPixels}"));
                        memoryStream.Seek(0, SeekOrigin.Begin);

                        imageUri = await this.blobStore.UploadBlobAsync(id, memoryStream);
                    }
                }

                await this.stickerStore.CreateStickerAsync(new Sticker
                {
                    Id = id,
                    ImageUri = imageUri,
                    Name = stickerViewModel.Name,
                    Keywords = stickerViewModel?.GetKeywordsList(),
                    State = StickerState.Active,
                });

                return this.RedirectToAction("Index");
            }

            return this.View(stickerViewModel);
        }

        /// <summary>
        /// GET: Stickers/Edit/5
        /// </summary>
        /// <param name="id">Id</param>
        /// <returns>Task Action Result</returns>
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Sticker sticker = await this.stickerStore.GetStickerAsync(id);
            if (sticker == null)
            {
                return this.HttpNotFound();
            }

            return this.View(new StickerViewModel(sticker));
        }

        /// <summary>
        /// POST: Stickers/Edit/5
        /// To protect from overposting attacks, please enable the specific properties you want to bind to, for
        /// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        /// </summary>
        /// <param name="stickerViewModel">Sticker View Model</param>
        /// <returns>Task Action Result</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Keywords")] StickerViewModel stickerViewModel)
        {
            if (this.ModelState.IsValid)
            {
                Sticker sticker = await this.stickerStore.GetStickerAsync(stickerViewModel.Id);

                sticker.Name = stickerViewModel.Name;
                sticker.Keywords = stickerViewModel?.GetKeywordsList();
                await this.stickerStore.UpdateStickerAsync(sticker);

                return this.RedirectToAction("Index");
            }

            return this.View(stickerViewModel);
        }

        /// <summary>
        /// GET: Stickers/Delete/5
        /// </summary>
        /// <param name="id">Id</param>
        /// <returns>Task Action Result</returns>
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Sticker sticker = await this.stickerStore.GetStickerAsync(id);
            if (sticker == null)
            {
                return this.HttpNotFound();
            }

            return this.View(new StickerViewModel(sticker));
        }

        /// <summary>
        /// POST: Stickers/Delete/5
        /// </summary>
        /// <param name="id">Id</param>
        /// <returns>Task Action Result</returns>
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Sticker sticker = await this.stickerStore.GetStickerAsync(id);
            if (sticker == null)
            {
                return this.HttpNotFound();
            }

            sticker.State = StickerState.SoftDeleted;
            await this.stickerStore.UpdateStickerAsync(sticker);

            return this.RedirectToAction("Index");
        }

        /// <summary>
        /// POST: Stickers/DeletePermanently/5
        /// </summary>
        /// <param name="id">Id</param>
        /// <returns>Task Action Result</returns>
        [HttpPost]
        [ActionName("DeletePermanently")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeletePermanentlyConfirmed(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            await this.stickerStore.DeleteStickerAsync(id);

            return this.RedirectToAction("Index");
        }

        /// <summary>
        /// POST: Stickers/Publish
        /// </summary>
        /// <returns>Task Action Result</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Publish()
        {
            var stickers = await this.stickerStore.GetStickersAsync();
            var activeStickers = stickers.Where(s => s.State == StickerState.Active);

            var configuration = new StickerConfigDTO
            {
                Images = activeStickers
                    .Select(s => new StickerDTO
                    {
                        ImageUri = s.ImageUri.AbsoluteUri,
                        Name = s.Name,
                        Keywords = s.Keywords.ToArray(),
                    })
                    .ToArray()
            };
            var configurationJson = JsonConvert.SerializeObject(configuration, Formatting.None);
            await this.blobStore.UploadBlobAsync("stickers.json", new MemoryStream(Encoding.UTF8.GetBytes(configurationJson)));

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }
    }
}

StickersTemplate.Configuration/Views/Stickers/Create.cshtml
@model StickersTemplate.Configuration.Models.StickerViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create Sticker</h2>


@using (Html.BeginForm("Create", "Stickers", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ImageUri, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img id="imgFile" src="#" alt="Selected image" class="hidden" width="280"/>
                <input class="form-control" type="file" name="File" accept="image/gif, image/jpeg, image/png" onchange="readURL(this);" />
                @Html.ValidationMessageFor(model => model.File, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @id = "txtName" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Keywords, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Keywords, new { htmlAttributes = new { @class = "form-control" } })
                <div class="small text-muted">Enter relevant search terms, separated by commas or spaces.</div>
                @Html.ValidationMessageFor(model => model.Keywords, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input id="btnSave" type="submit" value="Add sticker" class="btn btn-default" disabled />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script type="text/javascript">
    function readURL(input) {
        if (input.files && input.files[0]) {
            var file = input.files[0];

            var reader = new FileReader();
            reader.onload = function (e) {
                $("#imgFile")
                    .removeClass("hidden")
                    .attr("src", e.target.result);
                $("#btnSave")
                    .removeAttr("disabled");
            };
            reader.readAsDataURL(file);

            $("#txtName").val(file.name.replace(/\.[^/.]+$/, ""));
        }
    }
</script>

StickersTemplate.Configuration/Views/Stickers/Delete.cshtml
@model StickersTemplate.Configuration.Models.StickerViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete Sticker</h2>

<h3>Are you sure you want to delete this sticker?</h3>
<p>After you publish the changes, deleted stickers will no longer be returned by the messaging extension in Teams.</p>
<p>Messages that were sent with this sticker will continue to show the image.</p>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ImageUri)
        </dt>

        <dd>
            <img src="@Model.ImageUri" width="280" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Keywords)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Keywords)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

StickersTemplate.Configuration/Views/Stickers/Edit.cshtml
@model StickersTemplate.Configuration.Models.StickerViewModel    

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Sticker</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.ImageUri, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="@Model.ImageUri" width="280" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Keywords, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Keywords, new { htmlAttributes = new { @class = "form-control" } })
                <div class="small text-muted">Enter relevant search terms, separated by commas or spaces.</div>
                @Html.ValidationMessageFor(model => model.Keywords, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StickersTemplate.Configuration/Views/Stickers/Index.cshtml
@model IEnumerable<StickersTemplate.Configuration.Models.StickerViewModel>

@{
    ViewBag.Title = "Home";
}

<h2>Stickers</h2>

<p>
    @Html.ActionLink("Add new", "Create", null, new { @class = "btn btn-default" })
    <button id="btnPublish" class="btn btn-default">Update messaging extension</button>
    <div id="divPublishMessage"></div>
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(m => m.ImageUri)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.Name)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.Keywords)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <img src="@item.ImageUri" width="280" />
            </td>
            <td>
                @item.Name
            </td>
            <td>
                @item.Keywords
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>

<script type="text/javascript">
    function gettoken() {
        var token = '@Html.AntiForgeryToken()';
        token = $(token).val();
        return token;
    }

    $(document).ready(function () {
        $("#btnPublish").click(function () {
            $("#divPublishMessage").text("");
            $.ajax({
                type: "POST",
                url: "@Url.Action("Publish")",
                data: {
                    __RequestVerificationToken: gettoken(),
                },
                contentType: "application/x-www-form-urlencoded; charset=utf-8",
                success: function () {
                    $("#divPublishMessage")
                        .text("The messaging extension configuration was successfully updated.")
                        .removeClass("text-danger")
                        .addClass("text-success");
                },
                error: function () {
                    $("#divPublishMessage")
                        .text("There was an error updating the messaging extension.")
                        .addClass("text-danger")
                        .removeClass("text-success");
                }
            });
        });
    });
</script>